#!/bin/bash
LAB="lab-1"
INPUT=$LAB/input/
ACTUAL=$LAB/actual/
EXPECT=$LAB/expect/
PROJECT=../

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
WHITE='\033[0m'

checkComplexity () {
  if command -v pmccabe >/dev/null 2>&1;
    then
      PMCCABE=$(pmccabe $PROJECT*.h $PROJECT*.cpp | awk '{ if ($1 > 8) print $1 "\t" $NF}')
      if [ "$PMCCABE" != "" ]
        then
        printf "pmccabe......${RED}FAILED${WHITE}\n"
        echo "$PMCCABE"
      else
        printf "pmccabe......${GREEN}PASSED${WHITE}\n"
      fi
    else
      printf "pmccabe......${RED}UNINSTALLED${WHITE}: try running 'sudo-apt-get install pmccabe\n'"
  fi
}

compile () {
  echo "Compiling project..."
  g++ -g -Wall -std=c++11 $PROJECT*.cpp -o project
}

testfile () {
  ./project $INPUT$FILE $ACTUAL$FILE
  DIFF=$(diff $EXPECT$FILE $ACTUAL$FILE)
  if [ "$DIFF" != "" ]
    then
    printf "Test $FILE......${RED}FAILED${WHITE}\n"
  else
    printf "Test $FILE......${GREEN}PASSED${WHITE}\n"
  fi
}

case $1 in
  -h|--help)
    man ./manpage
  ;;
  -u|--update)
    echo "Updating File Paths (leave field empty to skip)"
    echo -n "    Lab Number: "
    read DIR
    if [ "$DIR" != "" ]
      then
        sed -i '2s|.*|LAB="lab-'$DIR'"|' test.sh
        printf "${YELLOW}    The variable \$LAB now contains \"$DIR\". Feel free to use it below...${WHITE}\n"
        DIR=""
    fi

    echo -n "    Path to input files (i.e. \$LAB/input): "
    read DIR
    if [ "$DIR" != "" ]
      then
        sed -i '3s|.*|INPUT='$DIR'/|' test.sh
        DIR=""
    fi

    echo -n "    Path to actual outputs (i.e. \$LAB/actual): "
    read DIR
    if [ "$DIR" != "" ]
      then
        sed -i '4s|.*|ACTUAL='$DIR'/|' test.sh
        DIR=""
    fi

    echo -n "    Path to expected outputs (i.e. \$LAB/expect): "
    read DIR
    if [ "$DIR" != "" ]
      then
        sed -i '5s|.*|EXPECT='$DIR'/|' test.sh
        DIR=""
    fi

    echo -n "    Path to project files (i.e. ../): "
    read DIR
    if [ "$DIR" != "" ]
      then
        sed -i '6s|.*|PROJECT='$DIR'/|' test.sh
        DIR=""
    fi
    printf "${GREEN}    UPDATE COMPLETE!${WHITE}\n"
    printf "${YELLOW}Note: paths can be updated manually by editing the variables on lines 1-6${WHITE}\n\n"
  ;;
  -v|--version)
    echo "1.0.1"
  ;;
  -p|--pmccabe)
    checkComplexity
  ;;
  -cf|-fc|-f)
    if [ "$1" == "-cf" ]||[ "$1" == "-fc" ]
      then
        compile
    fi
    FILE=$2
    if [ "$2" == "" ]
      then
        echo -n "Enter file name: "
        read FILE
    fi
    if [ -f $INPUT$FILE ];
      then
        testfile
      else
         echo "File '$FILE' does not exist. All tests must be located in '$INPUT'"
    fi
  ;;
  ""|-c)
    if [ "$1" == "-c" ]
      then
        compile
    fi
    echo "$LAB test results:"
    echo "-------------------"
    for FILE in $(ls $INPUT)
    do
        testfile
    done
    echo "-------------------"
    checkComplexity
  ;;
  *)
    echo "invalid options"
  ;;
esac
